### ISSUE TITLE
IC-Light Conditioning Node expects a Latent instead of an image

### ISSUE THREAD

**Issue by risunobushi** [kijai/ComfyUI-IC-Light#1]
Hey!
I'm guessing this is because the node was just updated, but I wanted to report a bug where the workflow can't run because the IC-Light Conditioning node is expecting a Latent instead of an image, but the input is set as a image only.

Log:
got prompt
Failed to validate prompt for output 36:
* ICLightConditioning 38:
  - Return type mismatch between linked nodes: foreground, IMAGE != LATENT
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
Prompt executed in 0.07 seconds

Thanks for all the hard work!

**Comment by kubilaykilinc** [comment]
I tried new Optional Background Workflow. But final image is very blurry. 
![image](https://github.com/kijai/ComfyUI-IC-Light/assets/18080130/7e7ca341-5db5-4084-8a7a-2ef5b7ee7286)

**Comment by risunobushi** [comment]
Thank you, you were lightning fast in fixing that and I happened to git pull in between updates!
