### ISSUE TITLE
where can I download your example workflow json

### ISSUE THREAD

**Issue by CPPAlien** [kijai/ComfyUI-IC-Light#10]
There is only images in the exampler folder, can you please paste the json file, thx.

**Comment by AiSatan** [comment]
you can load the png file instead of json, it contains the workflow and comfy supports it:

![image](https://github.com/kijai/ComfyUI-IC-Light/assets/2905049/0e12c106-85a6-4055-8387-2abc5b262b3b)

**Comment by kijai** [comment]
They are embedded in the .png indeed.
