### ISSUE TITLE
when i run on my comfyui, i got this error

### ISSUE THREAD

**Issue by Yww12** [kijai/ComfyUI-IC-Light#11]
Error occurred when executing LightSource:

tuple index out of range

File "/root/autodl-tmp/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/root/autodl-tmp/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/root/autodl-tmp/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-IC-Light/nodes.py", line 201, in execute
image = generate_gradient_image(width, height, start_color_rgb, end_color_rgb, multiplier, lightPosition)
File "/root/autodl-tmp/ComfyUI/custom_nodes/ComfyUI-IC-Light/utils/image.py", line 65, in generate_gradient_image
gradient_img[..., i] = start_color[i] + (end_color[i] - start_color[i]) * gradient

**Comment by kijai** [comment]
That was the simple light source example right? The node it uses was updated but the workflow not, so it errors out. Try the `ic_light_simple_light_multi_02.png` instead, it's pretty much the same, I'll delete the other one as I don't want to keep too many of these up to date.

**Comment by Yww12** [comment]
Thanks for your help,  I checked my workflow, i find the height of the resized image is set to 0. This will inevitably lead to errors.

**Comment by Yww12** [comment]
> That was the simple light source example right? The node it uses was updated but the workflow not, so it errors out. Try the `ic_light_simple_light_multi_02.png` instead, it's pretty much the same, I'll delete the other one as I don't want to keep too many of these up to date.
> 
> Or just re-create the simple light source node in the existing workflow.
