### ISSUE TITLE
I cannot find this node. Is there a need to install some custom extension point?

### ISSUE THREAD

**Issue by ottopan** [kijai/ComfyUI-IC-Light#13]
Searched for a long time and couldn't find it.
![image](https://github.com/kijai/ComfyUI-IC-Light/assets/18224971/3d68b205-05dc-4689-89aa-43bb695e1c21)

**Comment by kijai** [comment]
> Searched for a long time and couldn't find it. ![image](https://private-user-images.githubusercontent.com/18224971/329833408-3d68b205-05dc-4689-89aa-43bb695e1c21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDA1NDQsIm5iZiI6MTcxNTUwMDI0NCwicGF0aCI6Ii8xODIyNDk3MS8zMjk4MzM0MDgtM2Q2OGIyMDUtMDVkYy00Njg5LTg5YWEtNDNiYjY5NWUxYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA3NTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYzM2MzdlZGQxZGRiNjllNDRmNDVmYTgyMzc3ZjgwNjBkMTA2MGJlNjU5OGQxZjA3MWE5NDJiMzJlZWI2YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x8-1Mmpg0aWzJ6P-kF8XQLFYFWUc_Xh71bsEUn2SI3M)

You need to update KJNodes, all the curve stuff I keep there.
