### ISSUE TITLE
Error occurred when executing ICLightConditioning:  Sizes of tensors must match except in dimension 1. Expected size 1 but got size 4 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by davidchenhs** [kijai/ComfyUI-IC-Light#14]
Error occurred when executing ICLightConditioning:  Sizes of tensors must match except in dimension 1. Expected size 1 but got size 4 for tensor number 1 in the list.
![屏幕截图 2024-05-12 192812](https://github.com/kijai/ComfyUI-IC-Light/assets/164337292/958a6213-b654-429e-afba-77125336f836)
I noticed that cv2 was added in the requirements.txt  
I have installed it but the operation  report an error : No matching distribution found for cv2 
I guess if it's the reason why the condition nodes cannot work as well
Hope for reply!

**Comment by davidchenhs** [comment]
I've solved my problem through uninstalling the other versions.I've download too many IC-light versions LOL...

**Comment by kijai** [comment]
That error is because I updated the cond node to match the batch size automatically, and if you used the workflow without the update it would error like that. Also good point about the cv2, the requirement is wrong as it's supposed to be opencv-python, it's only used for the HDR node so it shouldn't affect anything else, and most people already have it installed anyways.

**Comment by Priestru** [comment]
I have this error, yet to understand how to resolve it.

**Comment by Priestru** [comment]
> I have this error, yet to understand how to resolve it.
> 
> ```
> !!! Exception during processing!!! Sizes of tensors must match except in dimension 1. Expected size 1 but got size 4 for tensor number 1 in the list.
> Traceback (most recent call last):
>   File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light\nodes.py", line 148, in encode
>     concat_latent = torch.cat((samples_1, samples_2), dim=1)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size 4 for tensor number 1 in the list.
> ```

Okay, I just updated all nodes and it helped.
