### ISSUE TITLE
How do I implement a workflow that keys out the foreground character and then automatically generates a background that matches the cue word and illuminates it correctly?

### ISSUE THREAD

**Issue by onlyjokers** [kijai/ComfyUI-IC-Light#15]
It seems that you can only upload a background image in the sample file, and you can't create a new background out of it.
I'm hoping to achieve something similar: [Text-Conditioned Model](https://github.com/lllyasviel/IC-Light?tab=readme-ov-file#text-conditioned-model)

**Comment by kijai** [comment]
You would need to mask your image, then make the masked area gray, and use that as foreground contioning. From the example workflows I shared, the normal map creation has one automatic masking to do that.

**Comment by onlyjokers** [comment]
> 您需要遮罩图像，然后将遮罩区域设置为灰色，并将其用作前景构图。从我分享的示例工作流来看，法线贴图创建有一个自动遮罩来做到这一点。
It worked out! Thanks! I think you can make and upload an example of this!

**Comment by onlyjokers** [comment]
> You would need to mask your image, then make the masked area gray, and use that as foreground contioning. From the example workflows I shared, the normal map creation has one automatic masking to do that.

It worked out! Thanks! I think you can make and upload an example of this!
