### ISSUE TITLE
Missing ImageResize file node 

### ISSUE THREAD

**Issue by He1wer** [kijai/ComfyUI-IC-Light#18]
![F1JA@M(GD`C(3(AOD7J8IB3](https://github.com/kijai/ComfyUI-IC-Light/assets/169737940/d2c47e29-55c0-47f5-8ab6-ca59bc0c1551)
Missing these nodes no matter how updated,what should I do ?

**Comment by AiSatan** [comment]
if you're using [Comfy manager](https://github.com/ltdrdata/ComfyUI-Manager), just use this option:

![image](https://github.com/kijai/ComfyUI-IC-Light/assets/2905049/4051e99f-7e2e-49bf-b25b-23f23e232e49)


if not, I use this nodes:

[https://github.com/Fannovel16/ComfyUI-Video-Matting](https://github.com/Fannovel16/ComfyUI-Video-Matting)
[https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes)
[https://github.com/cubiq/ComfyUI_essentials](https://github.com/cubiq/ComfyUI_essentials)
[https://github.com/kijai/ComfyUI-KJNodes](https://github.com/kijai/ComfyUI-KJNodes)

![image](https://github.com/kijai/ComfyUI-IC-Light/assets/2905049/b40b1339-c402-4e7c-8254-96119622e676)

**Comment by He1wer** [comment]
Maybe the version I installed is not right. Does anyone have the entire folder of the previous version that can be shared with me

**Comment by He1wer** [comment]
Oh thanks! But can I get the previous version?

**Comment by kijai** [comment]
> Oh thanks! But can I get the previous version?

Previous version of what? That node has not changed for months. If the whole essentials package is failing to load, you should first try just re-installing it.

**Comment by He1wer** [comment]
I've re-installed it dozens of times. Maybe it's my computer environment

**Comment by kijai** [comment]
> I've re-installed it dozens of times. Maybe it's my computer environment

Ok well that would take some troubleshooting with those nodes then, there should be an import error in the startup log that would tell us more.

For now you can use any other resize node instead, for example this combo of Comfy native resize node and my GetImageSizeAndCount would be almost the same:
![image](https://github.com/kijai/ComfyUI-IC-Light/assets/40791699/9c019b11-80bd-4df8-a4f7-f4331bb9710d)

**Comment by He1wer** [comment]
Okey,I'll try it,thanks bro

**Comment by kijai** [comment]
Also added my own Resize node finally, has some ease of use functionality I wanted anyways:
![image](https://github.com/kijai/ComfyUI-IC-Light/assets/40791699/ffeb762b-a880-4154-86cd-7f3ac4d3193f)
