### ISSUE TITLE
Something wrong with the diffusers model loader in the Ic-Light workflow

### ISSUE THREAD

**Issue by SeraphYDQ** [kijai/ComfyUI-IC-Light#19]
Got some problem with the diffusers model loader in the Ic-Light workflow.
Details are in the following picture.
![question](https://github.com/kijai/ComfyUI-IC-Light/assets/165343945/042feb41-9b60-419e-a857-08f1474d92ca)
Thoughts ???

**Comment by kijai** [comment]
This is not the repository for those nodes, you are using this: https://github.com/kijai/ComfyUI-IC-Light-Wrapper

I wouldn't recommend using the Wrapper version for anything but testing purposes, it doesn't support all features and was just an initial project to test and help comparing results with the native version (which is this current repository)
