### ISSUE TITLE
Torch error on install

### ISSUE THREAD

**Issue by vkleinmp** [kijai/ComfyUI-IC-Light#2]
Install: ['https://github.com/kijai/ComfyUI-IC-Light?tab=readme-ov-file']
Download: git clone 'https://github.com/kijai/ComfyUI-IC-Light?tab=readme-ov-file'
[!] C:\Temp\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
[!]   _torch_pytree._register_pytree_node(
[!]
0it [00:00, ?it/s]Cmd('git') failed due to: exit code(128)
0it [00:00, ?it/s]   cmdline: git clone -v --recursive --progress -- https://github.com/kijai/ComfyUI-IC-Light?tab=readme-ov-file C:\Temp\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light?tab=readme-ov-file
Install: ['https://github.com/kijai/ComfyUI-IC-Light?tab=readme-ov-file']
Download: git clone 'https://github.com/kijai/ComfyUI-IC-Light?tab=readme-ov-file'
[!] C:\Temp\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
[!]   _torch_pytree._register_pytree_node(
[!]
 Cmd('git') failed due to: exit code(128)
0it [00:00, ?it/s]  cmdline: git clone -v --recursive --progress -- https://github.com/kijai/ComfyUI-IC-Light?tab=readme-ov-file C:\Temp\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light?tab=readme-ov-file

**Comment by kijai** [comment]
That's a wrong install command, how are you trying to install this?

**Comment by vkleinmp** [comment]
I was so fucking blind and stupid. Thanks, it's working now.

**Comment by kijai** [comment]
> I was so fucking blind and stupid. Thanks, it's working now.

No worries, happens to the best of us!
