### ISSUE TITLE
After changing to the latest version, I can't get the pictures to come out.

### ISSUE THREAD

**Issue by yiwangsimple** [kijai/ComfyUI-IC-Light#21]
mac m1max, error message：
WARNING SHAPE MISMATCH diffusion_model.input_blocks.0.0.weight WEIGHT NOT MERGED torch.Size([320, 8, 3, 3]) != torch.Size([320, 4, 3, 3])
Merged with diffusion_model.input_blocks.0.0.weight channel changed from torch.Size([320, 4, 3, 3]) to [320, 8, 3, 3]

/Users/weiwei/ComfyUI/nodes.py:1408: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))

**Comment by yiwangsimple** [comment]
![截屏2024-05-16 16 11 35](https://github.com/kijai/ComfyUI-IC-Light/assets/121092793/0000f56d-fe89-449e-a0a6-c684290ac456)

**Comment by yiwangsimple** [comment]
[ComfyUI-IC-Light-Wrapper](https://github.com/kijai/ComfyUI-IC-Light-Wrapper)This version works fine.
![截屏2024-05-16 16 32 30](https://github.com/kijai/ComfyUI-IC-Light/assets/121092793/16b05c9f-7310-4f57-a457-55f4692229ba)

**Comment by shaxiaozz** [comment]
I also encountered the same problem, have you solved it?

**Comment by kijai** [comment]
Anyone getting this should make sure ComfyUI and the nodes are both updated.

**Comment by shaxiaozz** [comment]
@kijai I can make sure they are all up to date~
