### ISSUE TITLE
Anyone can help?

### ISSUE THREAD

**Issue by rongtian0927** [kijai/ComfyUI-IC-Light#24]
![image](https://github.com/kijai/ComfyUI-IC-Light/assets/123718340/91889f71-e370-4f16-b393-0f14b8cb83ed)

**Comment by kijai** [comment]
These nodes do not use UNETLoader, this is probably a mixup and you're trying to use: 

https://github.com/huchenlei/ComfyUI-IC-Light-Native with wrong models.
