### ISSUE TITLE
what is the "prev_image" in node of "simple light source"?

### ISSUE THREAD

**Issue by kunamin** [kijai/ComfyUI-IC-Light#30]
When an object image with a white background is used, the overall result appears brighter, which is good. However, I am curious about what effect this has.

**Comment by kijai** [comment]
It's only to make batching them simpler, mostly for the normal map generation that needs the subject lighted from 4 different directions, example use:
![image](https://github.com/kijai/ComfyUI-IC-Light/assets/40791699/f46c8c39-deb8-4cb1-9948-d61b0a4e10d8)
