### ISSUE TITLE
AnimateDiff support

### ISSUE THREAD

**Issue by EvgenyKashin** [kijai/ComfyUI-IC-Light#41]
Great work with implementing ICLight in ComfyUI, thanks! If you know, could you refer, what should I change/implement to make it work with [AimateDiff](https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved)? Now it's technically working, but it produces corrupted generations and shapes mismatches:
```
WARNING SHAPE MISMATCH diffusion_model.input_blocks.0.0.weight WEIGHT NOT MERGED torch.Size([320, 12, 3, 3]) != torch.Size([320, 4, 3, 3])
Merged with diffusion_model.input_blocks.0.0.weight channel changed from torch.Size([320, 4, 3, 3]) to [320, 12, 3, 3]
```

**Comment by kijai** [comment]
That warning always happens, it just means the workaround to apply the IC-Light weights as a model patch is working, normally it's not possible in Comfy when the channel amount doesn't match.

Probably for the same reason (different channel count) IC-Light doesn't work well with AnimateDiff. At least I never found AD settings that would be better to just running normal batch with fixed seed.

**Comment by EvgenyKashin** [comment]
Oh, I see, thank you for the detailed response.
