### ISSUE TITLE
Failed to validate prompt for output 36:

### ISSUE THREAD

**Issue by mattjohnpowell** [kijai/ComfyUI-IC-Light#7]
Hi,

I'm using the foreground workflow in the Readme, have updated / downloaded via the Manager the nodes and the model but get the below

Prompt executed in 0.14 seconds
got prompt
Failed to validate prompt for output 36:
* ICLightConditioning 38:
  - Return type mismatch between linked nodes: foreground, IMAGE != LATENT
Output will be ignored

![image](https://github.com/kijai/ComfyUI-IC-Light/assets/1314666/d429e58d-6736-4b5c-93e0-fc475266191b)

Any ideas what I'm doing wrong?

**Comment by AiSatan** [comment]
redownload png example, it was updated to fix this: #5

**Comment by mattjohnpowell** [comment]
Thank you
